# Generated by Django 3.0.3 on 2020-04-25 09:17

import api1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=api1.models.upload_path),
        ),
    ]
