# Generated by Django 3.0.3 on 2020-04-25 09:29

import api1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0002_auto_20200425_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=api1.models.upload_path)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
